apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yml
- deployment.yml
images:
- name: garugaru/garu-io-projects-api
  newName: garugaru/garu-io-projects-api
  newTag: 746a41a9924abbec2c7c24cf182c4c9b478b48e5
